### ISSUE TITLE
Custom Tus hooks to inspect headers and return response to uploader

### ISSUE THREAD

**Issue by rmharrison** [CDCgov/data-exchange-upload#46]
Before upload starts
- Inspect headers for required metadata
- Return a WARNING for suggested metadata
- Return an ERROR for required metadata

Con
- Extensions don't work like plugins; we'd need to rebuild docker images

**Recommend starting with the `pre-create` file hook.  See [comment](https://github.com/CDCgov/data-exchange-upload/issues/46#issuecomment-1372653682) below.**

**Comment by mkrystof** [comment]
If the protocol extension implementation does not work out there is another possible solution using tus webhooks.  In particular, the [`pre-create`](https://github.com/tus/tusd/blob/master/docs/hooks.md#pre-create) blocking file hook.

**pre-create**
*This event will be triggered before an upload is created, allowing you to run certain routines. For example, validating that specific metadata values are set, or verifying that a corresponding entity belonging to the upload (e.g. a user) exists. Because this event will result in a blocking hook, you can determine whether the upload should be created or rejected using the exit code. An exit code of 0 will allow the upload to be created and continued as usual. A non-zero exit code will reject an upload creation request, making it a good place for authentication and authorization. Please be aware that during this stage the upload ID will be an empty string and Storage will be null. This is because the entity has not been created and therefore this piece of information is not yet available.*

**Comment by mkrystof** [comment]
I was able to complete this task as part of the work to implement the supplemental tus API, which uses similar file hooks.
